import { Theme } from "theme.slint";

export component IconButton inherits Rectangle {
    in-out property icon <=> icon.source;
    callback clicked <=> touch.clicked;
    in-out property <bool> checked;

    width: 40px;
    height: 40px;
    border-width: touch.has-hover ? 1.5px : 1px;
    border-radius: 12px;
    opacity: touch.pressed ? 0.7 : 1.0;
    border-color: Theme.iconButtonBorderColor;

    icon:= Image {
        colorize: Theme.iconButtonImageOverlayColor;
        width: 20px;
        height: 20px;
    }

    touch := TouchArea {
        clicked => { root.checked = !root.checked }
     }
}