import { Theme } from "theme.slint";

export component LabelSmall inherits Text {
    font-size: Theme.labelFontSizeSmall;
    color: Theme.labelTextColor;
}

export component LabelMedium inherits Text {
    font-size: Theme.labelFontSizeMedium;
    color: Theme.labelTextColor;
}

export component LabelLarge inherits Text {
    font-size: Theme.labelFontSizeLarge;
    color: Theme.labelTextColor;
}
