use chrono_tz::{self, Tz};

pub struct Timezone {
    pub offset: i32,
    pub name: &'static str,
    pub location: &'static str,
    pub timezone: Tz,
}

pub const TIME_ZONES: [Timezone; 148] = [
    Timezone {
        offset: 0,
        name: "Coordinated Universal Time(UTC)",
        location: "Etc/GMT",
        timezone: Tz::UTC,
    },
    Timezone {
        offset: -10,
        name: "Hawaii",
        location: "Pacific/Honolulu",
        timezone: Tz::Pacific__Honolulu,
    },
    Timezone {
        offset: -9,
        name: "Alaska",
        location: "America/Anchorage",
        timezone: Tz::America__Anchorage,
    },
    Timezone {
        offset: -8,
        name: "Baja California",
        location: "America/Santa_Isabel",
        timezone: Tz::America__Santa_Isabel,
    },
    Timezone {
        offset: -7,
        name: "Chihuahua",
        location: "America/Chihuahua",
        timezone: Tz::America__Chihuahua,
    },
    Timezone {
        offset: -7,
        name: "La Paz",
        location: "America/Chihuahua",
        timezone: Tz::America__Chihuahua,
    },
    Timezone {
        offset: -7,
        name: "Mazatlan",
        location: "America/Chihuahua",
        timezone: Tz::America__Chihuahua,
    },
    Timezone {
        offset: -7,
        name: "Arizona",
        location: "America/Phoenix",
        timezone: Tz::America__Phoenix,
    },
    Timezone {
        offset: -6,
        name: "Central America",
        location: "America/Guatemala",
        timezone: Tz::America__Guatemala,
    },
    Timezone {
        offset: -6,
        name: "Saskatchewan",
        location: "America/Regina",
        timezone: Tz::America__Regina,
    },
    Timezone {
        offset: -6,
        name: "Guadalajara",
        location: "America/Mexico_City",
        timezone: Tz::America__Mexico_City,
    },
    Timezone {
        offset: -6,
        name: "Monterey",
        location: "America/Mexico_City",
        timezone: Tz::America__Mexico_City,
    },
    Timezone {
        offset: -6,
        name: "Mexico City",
        location: "America/Mexico_City",
        timezone: Tz::America__Mexico_City,
    },
    Timezone {
        offset: -5,
        name: "Bogota",
        location: "America/Bogota",
        timezone: Tz::America__Bogota,
    },
    Timezone {
        offset: -5,
        name: "Lima",
        location: "America/Bogota",
        timezone: Tz::America__Bogota,
    },
    Timezone {
        offset: -5,
        name: "Quito",
        location: "America/Bogota",
        timezone: Tz::America__Bogota,
    },
    Timezone {
        offset: -5,
        name: "Indiana (East)",
        location: "America/Indiana/Indianapolis",
        timezone: Tz::America__Indiana__Indianapolis,
    },
    Timezone {
        offset: -4,
        name: "Caracas",
        location: "America/Caracas",
        timezone: Tz::America__Caracas,
    },
    Timezone {
        offset: -4,
        name: "Atlantic Time (Canada)",
        location: "America/Halifax",
        timezone: Tz::America__Halifax,
    },
    Timezone {
        offset: -4,
        name: "Asuncion",
        location: "America/Asuncion",
        timezone: Tz::America__Asuncion,
    },
    Timezone {
        offset: -4,
        name: "Georgetown",
        location: "America/La_Paz",
        timezone: Tz::America__La_Paz,
    },
    Timezone {
        offset: -4,
        name: "La Paz",
        location: "America/La_Paz",
        timezone: Tz::America__La_Paz,
    },
    Timezone {
        offset: -4,
        name: "Manaus",
        location: "America/La_Paz",
        timezone: Tz::America__La_Paz,
    },
    Timezone {
        offset: -4,
        name: "San Juan",
        location: "America/La_Paz",
        timezone: Tz::America__La_Paz,
    },
    Timezone {
        offset: -4,
        name: "Cuiaba",
        location: "America/Cuiaba",
        timezone: Tz::America__Cuiaba,
    },
    Timezone {
        offset: -4,
        name: "Santiago",
        location: "America/Santiago",
        timezone: Tz::America__Santiago,
    },
    Timezone {
        offset: -3,
        name: "Newfoundland",
        location: "America/St_Johns",
        timezone: Tz::America__St_Johns,
    },
    Timezone {
        offset: -3,
        name: "Brasilia",
        location: "America/Sao_Paulo",
        timezone: Tz::America__Sao_Paulo,
    },
    Timezone {
        offset: -3,
        name: "Greenland",
        location: "America/Godthab",
        timezone: Tz::America__Godthab,
    },
    Timezone {
        offset: -3,
        name: "Cayenne",
        location: "America/Cayenne",
        timezone: Tz::America__Cayenne,
    },
    Timezone {
        offset: -3,
        name: "Fortaleza",
        location: "America/Cayenne",
        timezone: Tz::America__Cayenne,
    },
    Timezone {
        offset: -3,
        name: "Buenos Aires",
        location: "America/Argentina/Buenos_Aires",
        timezone: Tz::America__Argentina__Buenos_Aires,
    },
    Timezone {
        offset: -3,
        name: "Montevideo",
        location: "America/Montevideo",
        timezone: Tz::America__Montevideo,
    },
    Timezone {
        offset: -1,
        name: "Cape Verde",
        location: "Atlantic/Cape_Verde",
        timezone: Tz::Atlantic__Cape_Verde,
    },
    Timezone {
        offset: -1,
        name: "Azores",
        location: "Atlantic/Azores",
        timezone: Tz::Atlantic__Azores,
    },
    Timezone {
        offset: 0,
        name: "Casablanca",
        location: "Africa/Casablanca",
        timezone: Tz::Africa__Casablanca,
    },
    Timezone {
        offset: 0,
        name: "Monrovia",
        location: "Atlantic/Reykjavik",
        timezone: Tz::Atlantic__Reykjavik,
    },
    Timezone {
        offset: 0,
        name: "Reykjavik",
        location: "Atlantic/Reykjavik",
        timezone: Tz::Atlantic__Reykjavik,
    },
    Timezone {
        offset: 0,
        name: "Dublin",
        location: "Europe/London",
        timezone: Tz::Europe__London,
    },
    Timezone {
        offset: 0,
        name: "Edinburgh",
        location: "Europe/London",
        timezone: Tz::Europe__London,
    },
    Timezone {
        offset: 0,
        name: "Lisbon",
        location: "Europe/London",
        timezone: Tz::Europe__London,
    },
    Timezone {
        offset: 0,
        name: "London",
        location: "Europe/London",
        timezone: Tz::Europe__London,
    },
    Timezone {
        offset: 1,
        name: "Amsterdam",
        location: "Europe/Berlin",
        timezone: Tz::Europe__Berlin,
    },
    Timezone {
        offset: 1,
        name: "Berlin",
        location: "Europe/Berlin",
        timezone: Tz::Europe__Berlin,
    },
    Timezone {
        offset: 1,
        name: "Bern",
        location: "Europe/Berlin",
        timezone: Tz::Europe__Berlin,
    },
    Timezone {
        offset: 1,
        name: "Rome",
        location: "Europe/Berlin",
        timezone: Tz::Europe__Berlin,
    },
    Timezone {
        offset: 1,
        name: "Stockholm",
        location: "Europe/Berlin",
        timezone: Tz::Europe__Berlin,
    },
    Timezone {
        offset: 1,
        name: "Vienna",
        location: "Europe/Berlin",
        timezone: Tz::Europe__Berlin,
    },
    Timezone {
        offset: 1,
        name: "Brussels",
        location: "Europe/Paris",
        timezone: Tz::Europe__Paris,
    },
    Timezone {
        offset: 1,
        name: "Copenhagen",
        location: "Europe/Paris",
        timezone: Tz::Europe__Paris,
    },
    Timezone {
        offset: 1,
        name: "Madrid",
        location: "Europe/Paris",
        timezone: Tz::Europe__Paris,
    },
    Timezone {
        offset: 1,
        name: "Paris",
        location: "Europe/Paris",
        timezone: Tz::Europe__Paris,
    },
    Timezone {
        offset: 1,
        name: "West Central Africa",
        location: "Africa/Lagos",
        timezone: Tz::Africa__Lagos,
    },
    Timezone {
        offset: 1,
        name: "Belgrade",
        location: "Europe/Budapest",
        timezone: Tz::Europe__Budapest,
    },
    Timezone {
        offset: 1,
        name: "Bratislava",
        location: "Europe/Budapest",
        timezone: Tz::Europe__Budapest,
    },
    Timezone {
        offset: 1,
        name: "Budapest",
        location: "Europe/Budapest",
        timezone: Tz::Europe__Budapest,
    },
    Timezone {
        offset: 1,
        name: "Ljubljana",
        location: "Europe/Budapest",
        timezone: Tz::Europe__Budapest,
    },
    Timezone {
        offset: 1,
        name: "Prague",
        location: "Europe/Budapest",
        timezone: Tz::Europe__Budapest,
    },
    Timezone {
        offset: 1,
        name: "Sarajevo",
        location: "Europe/Warsaw",
        timezone: Tz::Europe__Warsaw,
    },
    Timezone {
        offset: 1,
        name: "Skopje",
        location: "Europe/Warsaw",
        timezone: Tz::Europe__Warsaw,
    },
    Timezone {
        offset: 1,
        name: "Warsaw",
        location: "Europe/Warsaw",
        timezone: Tz::Europe__Warsaw,
    },
    Timezone {
        offset: 1,
        name: "Zagreb",
        location: "Europe/Warsaw",
        timezone: Tz::Europe__Warsaw,
    },
    Timezone {
        offset: 1,
        name: "Windhoek",
        location: "Africa/Windhoek",
        timezone: Tz::Africa__Windhoek,
    },
    Timezone {
        offset: 2,
        name: "Athens",
        location: "Europe/Istanbul",
        timezone: Tz::Europe__Istanbul,
    },
    Timezone {
        offset: 2,
        name: "Bucharest",
        location: "Europe/Istanbul",
        timezone: Tz::Europe__Istanbul,
    },
    Timezone {
        offset: 2,
        name: "Istanbul",
        location: "Europe/Istanbul",
        timezone: Tz::Europe__Istanbul,
    },
    Timezone {
        offset: 2,
        name: "Helsinki",
        location: "Europe/Kiev",
        timezone: Tz::Europe__Kiev,
    },
    Timezone {
        offset: 2,
        name: "Kyiv",
        location: "Europe/Kiev",
        timezone: Tz::Europe__Kiev,
    },
    Timezone {
        offset: 2,
        name: "Riga",
        location: "Europe/Kiev",
        timezone: Tz::Europe__Kiev,
    },
    Timezone {
        offset: 2,
        name: "Sofia",
        location: "Europe/Kiev",
        timezone: Tz::Europe__Kiev,
    },
    Timezone {
        offset: 2,
        name: "Tallinn",
        location: "Europe/Kiev",
        timezone: Tz::Europe__Kiev,
    },
    Timezone {
        offset: 2,
        name: "Vilnius",
        location: "Europe/Kiev",
        timezone: Tz::Europe__Kiev,
    },
    Timezone {
        offset: 2,
        name: "Cairo",
        location: "Africa/Cairo",
        timezone: Tz::Africa__Cairo,
    },
    Timezone {
        offset: 2,
        name: "Damascus",
        location: "Asia/Damascus",
        timezone: Tz::Asia__Damascus,
    },
    Timezone {
        offset: 2,
        name: "Amman",
        location: "Asia/Amman",
        timezone: Tz::Asia__Amman,
    },
    Timezone {
        offset: 2,
        name: "Harare",
        location: "Africa/Johannesburg",
        timezone: Tz::Africa__Johannesburg,
    },
    Timezone {
        offset: 2,
        name: "Pretoria",
        location: "Africa/Johannesburg",
        timezone: Tz::Africa__Johannesburg,
    },
    Timezone {
        offset: 2,
        name: "Pretoria",
        location: "Africa/Johannesburg",
        timezone: Tz::Africa__Johannesburg,
    },
    Timezone {
        offset: 2,
        name: "Jerusalem",
        location: "Asia/Jerusalem",
        timezone: Tz::Asia__Jerusalem,
    },
    Timezone {
        offset: 2,
        name: "Beirut",
        location: "Asia/Beirut",
        timezone: Tz::Asia__Beirut,
    },
    Timezone {
        offset: 3,
        name: "Baghdad",
        location: "Asia/Baghdad",
        timezone: Tz::Asia__Baghdad,
    },
    Timezone {
        offset: 3,
        name: "Minsk",
        location: "Europe/Minsk",
        timezone: Tz::Europe__Minsk,
    },
    Timezone {
        offset: 3,
        name: "Kuwait",
        location: "Asia/Riyadh",
        timezone: Tz::Asia__Riyadh,
    },
    Timezone {
        offset: 3,
        name: "Riyadh",
        location: "Asia/Riyadh",
        timezone: Tz::Asia__Riyadh,
    },
    Timezone {
        offset: 3,
        name: "Nairobi",
        location: "Africa/Nairobi",
        timezone: Tz::Africa__Nairobi,
    },
    Timezone {
        offset: 3,
        name: "Tehran",
        location: "Asia/Tehran",
        timezone: Tz::Asia__Tehran,
    },
    Timezone {
        offset: 4,
        name: "Moscow",
        location: "Europe/Moscow",
        timezone: Tz::Europe__Moscow,
    },
    Timezone {
        offset: 4,
        name: "St. Petersburg",
        location: "Europe/Moscow",
        timezone: Tz::Europe__Moscow,
    },
    Timezone {
        offset: 4,
        name: "Volgograd",
        location: "Europe/Moscow",
        timezone: Tz::Europe__Moscow,
    },
    Timezone {
        offset: 4,
        name: "Tbilisi",
        location: "Asia/Tbilisi",
        timezone: Tz::Asia__Tbilisi,
    },
    Timezone {
        offset: 4,
        name: "Yerevan",
        location: "Asia/Yerevan",
        timezone: Tz::Asia__Yerevan,
    },
    Timezone {
        offset: 4,
        name: "Abu Dhabi",
        location: "Asia/Dubai",
        timezone: Tz::Asia__Dubai,
    },
    Timezone {
        offset: 4,
        name: "Muscat",
        location: "Asia/Dubai",
        timezone: Tz::Asia__Dubai,
    },
    Timezone {
        offset: 4,
        name: "Baku",
        location: "Asia/Baku",
        timezone: Tz::Asia__Baku,
    },
    Timezone {
        offset: 4,
        name: "Port Louis",
        location: "Indian/Mauritius",
        timezone: Tz::Indian__Mauritius,
    },
    Timezone {
        offset: 4,
        name: "Kabul",
        location: "Asia/Kabul",
        timezone: Tz::Asia__Kabul,
    },
    Timezone {
        offset: 5,
        name: "Tashkent",
        location: "Asia/Tashkent",
        timezone: Tz::Asia__Tashkent,
    },
    Timezone {
        offset: 5,
        name: "Islamabad",
        location: "Asia/Karachi",
        timezone: Tz::Asia__Karachi,
    },
    Timezone {
        offset: 5,
        name: "Karachi",
        location: "Asia/Karachi",
        timezone: Tz::Asia__Karachi,
    },
    Timezone {
        offset: 5,
        name: "Sri Jayewardenepura Kotte",
        location: "Asia/Colombo",
        timezone: Tz::Asia__Colombo,
    },
    Timezone {
        offset: 5,
        name: "Chennai",
        location: "Asia/Kolkata",
        timezone: Tz::Asia__Kolkata,
    },
    Timezone {
        offset: 5,
        name: "Kolkata",
        location: "Asia/Kolkata",
        timezone: Tz::Asia__Kolkata,
    },
    Timezone {
        offset: 5,
        name: "Mumbai",
        location: "Asia/Kolkata",
        timezone: Tz::Asia__Kolkata,
    },
    Timezone {
        offset: 5,
        name: "New Delhi",
        location: "Asia/Kolkata",
        timezone: Tz::Asia__Kolkata,
    },
    Timezone {
        offset: 5,
        name: "Kathmandu",
        location: "Asia/Kathmandu",
        timezone: Tz::Asia__Kathmandu,
    },
    Timezone {
        offset: 6,
        name: "Astana",
        location: "Asia/Almaty",
        timezone: Tz::Asia__Almaty,
    },
    Timezone {
        offset: 6,
        name: "Dhaka",
        location: "Asia/Dhaka",
        timezone: Tz::Asia__Dhaka,
    },
    Timezone {
        offset: 6,
        name: "Yekaterinburg",
        location: "Asia/Yekaterinburg",
        timezone: Tz::Asia__Yekaterinburg,
    },
    Timezone {
        offset: 6,
        name: "Yangon",
        location: "Asia/Yangon",
        timezone: Tz::Asia__Yangon,
    },
    Timezone {
        offset: 7,
        name: "Bangkok",
        location: "Asia/Bangkok",
        timezone: Tz::Asia__Bangkok,
    },
    Timezone {
        offset: 7,
        name: "Hanoi",
        location: "Asia/Bangkok",
        timezone: Tz::Asia__Bangkok,
    },
    Timezone {
        offset: 7,
        name: "Jakarta",
        location: "Asia/Bangkok",
        timezone: Tz::Asia__Bangkok,
    },
    Timezone {
        offset: 7,
        name: "Novosibirsk",
        location: "Asia/Novosibirsk",
        timezone: Tz::Asia__Novosibirsk,
    },
    Timezone {
        offset: 8,
        name: "Krasnoyarsk",
        location: "Asia/Krasnoyarsk",
        timezone: Tz::Asia__Krasnoyarsk,
    },
    Timezone {
        offset: 8,
        name: "Ulaanbaatar",
        location: "Asia/Ulaanbaatar",
        timezone: Tz::Asia__Ulaanbaatar,
    },
    Timezone {
        offset: 8,
        name: "Beijing",
        location: "Asia/Shanghai",
        timezone: Tz::Asia__Shanghai,
    },
    Timezone {
        offset: 8,
        name: "Chongqing",
        location: "Asia/Shanghai",
        timezone: Tz::Asia__Shanghai,
    },
    Timezone {
        offset: 8,
        name: "Hong Kong",
        location: "Asia/Shanghai",
        timezone: Tz::Asia__Shanghai,
    },
    Timezone {
        offset: 8,
        name: "Urumqi",
        location: "Asia/Shanghai",
        timezone: Tz::Asia__Shanghai,
    },
    Timezone {
        offset: 8,
        name: "Perth",
        location: "Australia/Perth",
        timezone: Tz::Australia__Perth,
    },
    Timezone {
        offset: 8,
        name: "Kuala Lumpur",
        location: "Asia/Singapore",
        timezone: Tz::Asia__Singapore,
    },
    Timezone {
        offset: 8,
        name: "Singapore",
        location: "Asia/Singapore",
        timezone: Tz::Asia__Singapore,
    },
    Timezone {
        offset: 8,
        name: "Taipei",
        location: "Asia/Taipei",
        timezone: Tz::Asia__Taipei,
    },
    Timezone {
        offset: 9,
        name: "Irkutsk",
        location: "Asia/Irkutsk",
        timezone: Tz::Asia__Irkutsk,
    },
    Timezone {
        offset: 9,
        name: "Seoul",
        location: "Asia/Seoul",
        timezone: Tz::Asia__Seoul,
    },
    Timezone {
        offset: 9,
        name: "Osaka",
        location: "Asia/Tokyo",
        timezone: Tz::Asia__Tokyo,
    },
    Timezone {
        offset: 9,
        name: "Sapporo",
        location: "Asia/Tokyo",
        timezone: Tz::Asia__Tokyo,
    },
    Timezone {
        offset: 9,
        name: "Tokyo",
        location: "Asia/Tokyo",
        timezone: Tz::Asia__Tokyo,
    },
    Timezone {
        offset: 9,
        name: "Darwin",
        location: "Australia/Darwin",
        timezone: Tz::Australia__Darwin,
    },
    Timezone {
        offset: 9,
        name: "Adelaide",
        location: "Australia/Adelaide",
        timezone: Tz::Australia__Adelaide,
    },
    Timezone {
        offset: 10,
        name: "Hobart",
        location: "Australia/Hobart",
        timezone: Tz::Australia__Hobart,
    },
    Timezone {
        offset: 10,
        name: "Yakutsk",
        location: "Asia/Yakutsk",
        timezone: Tz::Asia__Yakutsk,
    },
    Timezone {
        offset: 10,
        name: "Brisbane",
        location: "Australia/Brisbane",
        timezone: Tz::Australia__Brisbane,
    },
    Timezone {
        offset: 10,
        name: "Guam",
        location: "Pacific/Port_Moresby",
        timezone: Tz::Pacific__Port_Moresby,
    },
    Timezone {
        offset: 10,
        name: "Port Moresby",
        location: "Pacific/Port_Moresby",
        timezone: Tz::Pacific__Port_Moresby,
    },
    Timezone {
        offset: 10,
        name: "Canberra",
        location: "Australia/Sydney",
        timezone: Tz::Australia__Sydney,
    },
    Timezone {
        offset: 10,
        name: "Melbourne",
        location: "Australia/Sydney",
        timezone: Tz::Australia__Sydney,
    },
    Timezone {
        offset: 10,
        name: "Sydney",
        location: "Australia/Sydney",
        timezone: Tz::Australia__Sydney,
    },
    Timezone {
        offset: 11,
        name: "Vladivostok",
        location: "Asia/Vladivostok",
        timezone: Tz::Asia__Vladivostok,
    },
    Timezone {
        offset: 11,
        name: "Solomon Islands",
        location: "Pacific/Guadalcanal",
        timezone: Tz::Pacific__Guadalcanal,
    },
    Timezone {
        offset: 11,
        name: "New Caledonia",
        location: "Pacific/Guadalcanal",
        timezone: Tz::Pacific__Guadalcanal,
    },
    Timezone {
        offset: 12,
        name: "Fiji",
        location: "Pacific/Fiji",
        timezone: Tz::Pacific__Fiji,
    },
    Timezone {
        offset: 12,
        name: "Marshall Islands",
        location: "Pacific/Fiji",
        timezone: Tz::Pacific__Fiji,
    },
    Timezone {
        offset: 12,
        name: "Magadan",
        location: "Asia/Magadan",
        timezone: Tz::Asia__Magadan,
    },
    Timezone {
        offset: 12,
        name: "Auckland",
        location: "Pacific/Auckland",
        timezone: Tz::Pacific__Auckland,
    },
    Timezone {
        offset: 12,
        name: "Wellington",
        location: "Pacific/Auckland",
        timezone: Tz::Pacific__Auckland,
    },
    Timezone {
        offset: 13,
        name: "Nuku'alofa",
        location: "Pacific/Tongatapu",
        timezone: Tz::Pacific__Tongatapu,
    },
    Timezone {
        offset: 13,
        name: "Samoa",
        location: "Pacific/Apia",
        timezone: Tz::Pacific__Apia,
    },
];
