import { Theme } from "controls/theme.slint";
import { GridView } from "controls/grid_view.slint";
import { TimeZoneInfo } from "controls/timezone_info.slint";
import { Header } from "header.slint";
import { TimeZoneInfo, DataAdapter } from "data_adapter.slint";
import { CityListPopup } from "city_list_popup.slint";

export { DataAdapter }

export component AppWindow inherits Window {
    title: "tymoz";
    preferred-width: 1200px;
    preferred-height: 800px;
    min-width: 620px;
    min-height: 720px;
    background: Theme.appBackgroundColor;

    VerticalLayout {
        spacing: 5px;
        padding: 10px;

        Header {
            date_time <=> DataAdapter.date_time;
            add_clicked => {
                popup.visible = true;
            }
        }

        Rectangle {
            vertical-stretch: 1;

            view := GridView {
                viewport-height: Math.round(DataAdapter.selected_cities_model.length / self.columns) * 180px;
                viewport-width: parent.width;

                for tz[index] in DataAdapter.selected_cities_model: TimeZoneInfo {
                    width: view.expectedWidth * 1px;
                    height: view.preferredCellHeight * 1px;
                    x: (Math.mod(index, view.columns)) * self.width ;
                    y: Math.floor(index / view.columns) * self.height;
                    city: tz.city;
                    time_now: tz.timenow;
                    offset: tz.offset;
                    date: tz.date;
                    is_ahead: tz.is-ahead;
                    timezone: tz.timezone;
                }
            }
        }
    }

    popup := CityListPopup {
        width: parent.width;
        height: parent.height;
        visible: false;

        add_city(index) => {
            DataAdapter.add_city(index);
        }
    }
}
